//===============================================================================
//You are given two strings s and t. String t is generated by random shuffling string s and then add one more letter at a random position. Return the letter that was added to t.
//===============================================================================

//Constraints
//1. Worse case: O(N ** 2)
//2. t.length == s.length + 1
//3. s and t consist of lower-case English letters

//Steps
//1. Create two empty objects. One object stores frequencyCounter for s, other for t
//2. Use a for loop to iterate over each string - initialize into each object
//3. Use a for in loop. Create a conditional to check if key exists in t compared to s. If not, return key. 2nd conditional checks if value is not the same, return key.

function findTheDifference(s,t) {
    let freqCounter1 = {};
    let freqCounter2 = {};

    for (let i = 0; i < s.length; i++) {
        freqCounter1[s[i]] = freqCounter1[s[i]] ? freqCounter1[s[i]] +=1 : freqCounter1[s[i]] = 1;
    }
    for (let i = 0; i < t.length; i++) {
        freqCounter2[t[i]] = freqCounter2[t[i]] ? freqCounter2[t[i]] +=1 : freqCounter2[t[i]] = 1;
    }

    for (key in freqCounter2) {
        if (!(key in freqCounter1)) {
            return key
        }
        if (freqCounter2[key] !== freqCounter1[key]) {
            return key
        }
    }
}

console.log(findTheDifference("abcd", "abcdd"))
